var EN = {
    about_p1: "Knowing yourself is the first step to knowing the world. I believe the world is fluid, growth is compound, and practice is the only standard of truth.",
    about_p2: "Movement keeps body and spirit alive; reading and reflection expand the boundaries of mind. Each day is a new act of self-reinvention.",
    about_title: "About",
    bne0: "1. Quickly calms emotions, relieves anxiety and panic.",
    bne1: "2. Activates parasympathetic nervous system, helps sleep.",
    bne2: "3. Reduces cortisol and body stress response.",
    bne3: "4. Regulates heart rate, relieving palpitations.",
    bne4: "5. Anytime, anywhere—no tools, zero threshold.",
    bne5: "6. Long-term improves breathing patterns and cardio function.",
    bns0: "1. Place the tip of your tongue against the gum behind your upper front teeth.",
    bns1: "2. Close your mouth and inhale slowly through your nose for 4 seconds.",
    bns2: "3. Hold your breath for 7 seconds.",
    bns3: "4. Exhale slowly through mouth for 8 seconds.",
    bns4: "5. One full breath. Repeat 4-6 times per set.",
    body_active: "Brain Activation Methods",
    body_intro: "Body is the vessel of the soul. In its finest state, it carries the deepest thoughts.",
    body_rest: "Deep Rest Methods",
    body_title: "Body Manual",
    conclusion_16pf: "16PF uses \"16 Source Traits\" as its framework. Higher scores (0-4) indicate more pronounced traits:\n\n1. Interpersonal & Emotional Traits\nWarmth (Score 3): High range. Strong interpersonal affinity, easily builds trusting, empathetic relationships.\nEmotional Stability (Score 3.2): High range. Excellent emotional regulation, remains composed under pressure and change.\n\n2. Cognitive & Decision-Making Traits\nReasoning (Score 3.4): High range. Outstanding abstract thinking and logical analysis, excels at deconstructing complex problems.\nDominance (Score 3.5): High range. Strong opinions and leadership, tends to lead in decision-making with pronounced competitiveness.\n\n3. Behavioral Style Traits\nLiveliness (Score 1.9): Low range. Lower outward energy expression, prefers low-stimulation, calm environments suited to \"less noise, more depth.\"\nRule-Consciousness (Score 1.8): Low range. Does not blindly follow authority or fixed rules; flexible and goal-oriented in approach.\nVigilance (Score 1.6): Low range. High interpersonal trust, low suspicion and defensiveness, more open in interactions.\nOpenness to Change (Score 3.4): High range. Highly receptive to new things and methods, not attached to fixed patterns.\n\n4. Self Traits\nSelf-Reliance (Score 3.3): High range. Strong independence, self-directed in planning and meeting needs.\nTension (Score 1.2): Low range. Relaxed psychological state, rarely experiences excessive impatience or anxiety.",
    conclusion_epq: "EPQ uses \"Lie (L), Extraversion (E), Neuroticism (N), Psychoticism (P)\" as its framework. Percentile scores represent relative standing in the norm group:\n\n1. Lie Scale (L): Good Response Validity\nScore 11 (55th percentile), moderate range. No significant deliberate embellishment or concealment; results genuinely reflect personality traits.\n\n2. Extraversion Scale (E): Ambivert — Balanced Social-Solitude Needs\nScore 11 (52nd percentile), in the middle range between typical extraversion and introversion.\nTraits: Neither depends on socializing for energy nor avoids interpersonal contact. Engages naturally but prefers moderate boundaries, with a balanced behavioral rhythm.\n\n3. Neuroticism Scale (N): Outstanding Emotional Stability\nScore 10 (41st percentile), notably below the norm average.\nTraits: Lower frequency and intensity of negative emotional arousal. Strong emotional regulation under stress and conflict, with a more stable psychological state.\n\n4. Psychoticism Scale (P): Good Interpersonal Fit\nScore 7 (30th percentile), low range (Psychoticism is not \"psychosis\" but an index of interpersonal detachment and impulsivity).\nTraits: Mild interpersonal style, good empathy; adapts well to environments and collaborates with others without notable coldness or antagonism.",
    conclusion_neo: "The Big Five uses \"Openness (O), Conscientiousness (C), Extraversion (E), Agreeableness (A), Neuroticism (N)\" as its core framework. Percentile scores reflect trait prominence within the norm group:\n\n1. Openness (O): Outstanding Cognitive Flexibility & Curiosity\nOverall 68%, core facets (Deliberation, Openness to Values) at 84%, high range.\nTraits: Exceptionally receptive to new experiences, diverse values, and abstract thinking. Cognitive style combines creativity with inclusiveness—willing to explore new domains while rationally embracing different perspectives.\n\n2. Neuroticism (N): Exceptional Emotional Resilience\nOverall 26%, core facets (Anxiety, Angry Hostility) both below 34%, significantly below norm.\nTraits: High threshold for negative emotions (anxiety, irritability, depression) with rapid recovery speed. Emotionally stable under pressure and change, rarely experiences excessive emotionality.\n\n3. Conscientiousness (C): Goal-Oriented with Flexibility\nOverall 62%, core facets (Competence, Order) at 78%, moderately high range.\nTraits: Possesses both responsibility and planning ability, able to advance tasks orderly; yet won’t fall into rigidity from over-adherence to rules, can flexibly adjust behavioral rhythm as needed.\n\n4. Agreeableness (A): Gentle Yet Boundaried\nOverall 53%, moderate range.\nTraits: Capable of empathy and collaboration while maintaining reasonable self-boundaries. Won’t over-accommodate others—displays \"kind but not submissive\" traits in interpersonal interactions.\n\n5. Extraversion (E): Social Energy Focused on Deep Connection\nOverall 47%, moderately low range.\nTraits: Not \"socially anxious\" but rather social needs centered on \"deep connection.\" Prefers low-stimulation, calm environments; maintains good psychological state when alone; social energy is allocated more sparingly.",
    contact_copy_done: "Copied ✓",
    contact_intro: "If anything resonates, feel free to write. Click to copy email.",
    contact_title: "Contact",
    fb0: "1. Integrity: Walk the talk. Notify ahead when plans change.",
    fb1: "2. Accountability: Solve first, review later. No blame-shifting.",
    fb2: "3. Emotional Stability: Address issues, not people.",
    fb3: "4. Win-Win Mindset: Share, contribute both ways. No one-sided takers.",
    fb4: "5. Bottom Line: Play by the rules. Earn it fairly.",
    fb5: "6. Sincerity: Communicate directly. No behind-the-back moves.",
    fc0: "1. Active Learning: Stay curious beyond the textbook.",
    fc1: "2. Continuous Growth: Have your own rhythm of growth and self-review.",
    fc2: "3. Critical Thinking: See issues rationally and listen to differing views.",
    fc3: "4. Reliability: Don’t ghost. Update on progress.",
    fc4: "5. Boundary Respect: Have boundaries and respect others’. No crossing lines.",
    fc5: "6. Open Mind: Embrace new ideas. Dare to err and grow from setbacks.",
    fc6: "7. Health Management: Regular routine. Don’t chronically burn out. Stay active.",
    fc7: "8. Time Mastery: Command fragmented time. Sustain deep focus when working.",
    footer: "© 2026 Julian Silas. The road ahead is long—learn humbly, verify carefully.",
    friend_section1: "Section 1: Basic Requirements",
    friend_section2: "Section 2: Core Requirements",
    friend_section3: "Section 3: Deal-Breakers",
    fv0: "1. Chronic Unreliability: Frequent no-shows, broken promises without remorse.",
    fv1: "2. Blame-Shifting: Grabs credit, dodges blame, never self-reflects.",
    fv2: "3. Emotional Attacks: Explodes easily, silent treatment or public outbursts.",
    fv3: "4. Extreme Selfishness: Wants handouts but never gives back.",
    fv4: "5. No Integrity: Cheats, plagiarizes, fabricates. Might betray friends.",
    fv5: "6. Two-Faced: Stirs drama behind backs, never confronts directly.",
    hero_about: "Know Me",
    hero_contact: "Contact Me",
    hero_desc: "Knowing yourself is the first step to knowing the world.",
    hero_hi: "Hi, I’m",
    hero_name: "Julian Silas",
    hero_sub: "As the Delphic maxim goes: &ldquo;Know Thyself (Gnothi Seauton)&rdquo;&mdash;&mdash;this is not a command, but an invitation: an invitation into the deepest, most honest conversation with yourself.",
    interview_cta: "These 23 Questions are not just me asking you—they are a bridge of mutual understanding.",
    interview_cta2: "Many people, after talking, realize they have never truly examined themselves this deeply; and in the process, I too will come to know you more deeply.",
    interview_cta3: "Rediscover yourself through answering, see each other through dialogue.",
    interview_intro: "Interview · 23 Questions to Spark a Genuine Conversation.",
    interview_invite_p1: "These 23 Questions are not just me asking you—they are a bridge of mutual understanding.",
    interview_invite_p2: "Many people, after talking, realize they have never truly examined themselves this deeply; and in the process, I too will come to know you more deeply.",
    interview_invite_title: "Not Just Me Asking",
    interview_reflect: "Rediscover yourself",
    interview_see: "See each other",
    interview_title: "What I’m Working On",
    interview_intro_full: "Interview · 23 Questions to Spark a Genuine Conversation.",
    interview_invite_html: "<strong>These 23 Questions are not just me asking you—they are a bridge of mutual understanding.</strong><br><br>Many people, after talking, realize they have never truly examined themselves this deeply;<br>and in the process, I too will come to know you more deeply.<br><br><span class=\"trait-label\">Rediscover yourself</span> through answering,<br><span class=\"trait-label\">See each other</span> through dialogue.<br><br>If you are willing to sit down for an hour,<br>for a face-to-face honest conversation—<br><strong>I am all ears, and I guarantee you will gain unexpected insights.</strong>",

    interview_collapse: "Collapse 23 Questions ▴",
    interview_expand: "Expand 23 Questions ▾",
    login_email_btn: "Email Login",
    login_github_btn: "GitHub Login",
    login_has_account: "Already have an account?",
    login_no_account: "Don’t have an account?",
    login_placeholder_email: "Email address",
    login_placeholder_pwd: "Password",
    login_title: "Login",
    logo: "Julian Silas",
    love_attachment: "Attachment in Love",
    love_choice: "Choice in Love",
    love_intro: "Why do some people remain fiercely loyal in love, even to the point of dying for it, while others are recklessly promiscuous and have never truly loved? Why, when love brings such pain, do people flock to it anyway?",
    love_loss: "The Death of Love",
    love_mechanism: "The Mechanism of Love—Hormones, Nerves, and Positive Feedback",
    love_origin: "The Origin of Love: Evolution—All for Survival and Continuity",
    love_p0: "Over millions of years of survival and reproduction, genes favoring survival were retained while carriers of disadvantageous genes perished. Through continuous evolution, the neurons of romantic love first emerged in human ancestors about 4 million years ago. At that time, love’s function was to increase reproductive success, provide stable nurturing environments for offspring, promote cooperation and group cohesion, and enhance survival fitness. Yet, if that were all, how could love shape such richly diverse forms in modern life?",
    love_p1: "When we are with our beloved, dopamine-rich areas of the brain activate—regions linked to pleasure, arousal, focused attention, and reward-seeking motivation. Oxytocin and vasopressin rise, reducing anxiety, enhancing trust, inhibiting betrayal, and strengthening intimate contact.",
    love_p2: "When people are seen, respected, favored, and accepted by their beloved, dopamine, oxytocin, and vasopressin all rise, creating feelings of joy, safety, calm, and happiness—driving them toward more intimate contact and continually reinforcing the romantic relationship. But do not forget: the brain has a natural homeostatic counterbalance. After these positive events, it will reverse-regulate, generating negative emotions to restore equilibrium.",
    love_p3: "Romantic love shares the same reward pathways as addictive behaviors. The dopamine rush creates euphoria; when the lover is absent, craving and withdrawal-like anxiety set in—driving reunion-seeking behavior. This is why early romantic love resembles “addiction.”",
    love_p4: "In the early stages of love, serotonin drops significantly, reducing impulse control and intensifying obsessive thoughts about the beloved—even interfering with normal eating and sleep.",
    love_p5: "As attachment deepens, oxytocin and vasopressin take over, bringing calm, trust, and long-term bonding—transitioning from passionate love to companionate love.",
    love_p6: "Long-term relationships also recruit the anterior cingulate cortex and other empathy regions, enabling partners to genuinely share each other’s pain and joy—the neural basis for “two becoming one.”",
    love_p7: "Love, from its evolutionary origin, is a mechanism for survival and continuity; from its neural foundation, it is a chemical cascade of reward, attachment, and homeostatic counterbalance; from its phenomenological experience, it is a complex mix of euphoria, pain, obsession, calm, choice, and commitment.",
    love_p8: "Understanding this, we can better grasp why love is at once the most beautiful and the most painful of human experiences—and why, for thousands of years, it has never ceased to captivate and mystify us.",
    love_p9: "Love is not just a feeling; it is a choice. A choice to continue choosing this person, again and again. And what makes that choice possible is not hormones alone, but the unique bond built through shared time, mutual understanding, and love that was or will be created together.",
    love_unique: "The Uniqueness of Love",
    love_origin_p: "Over millions of years of survival and reproduction, genes favoring survival were retained while carriers of disadvantageous genes perished. Through continuous evolution, the neurons of romantic love first emerged in human ancestors about 4 million years ago. At that time, love’s function was to increase reproductive success, provide stable nurturing environments for offspring, promote cooperation and group cohesion, and enhance survival fitness. Yet, if that were all, how could love shape such richly diverse forms in modern life?",
    love_mechanism_p2: "When we are seen, respected, favored, and accepted by our beloved, dopamine, oxytocin, and vasopressin all rise, creating feelings of joy, warmth, peace, and sweetness. These feelings in turn drive us to see, respect, favor, and accept others—forming a positive feedback loop. Cycle after cycle, love emerges and flows between us.",
    moment_2023: "Enlightenment · Breaking Through to Find Myself",
    moment_2024: "Seeking · Reading & Self-Awareness",
    moment_2025: "Questioning · Between the World and Myself",
    moment_2026: "Completion · Becoming Who I Am",
    moments_intro: "From 2023 to 2026, four years of inner journeys and footprints. Click to read.",
    moments_title: "Moments",
    nav_about: "About",
    nav_body: "Body",
    nav_contact: "Contact",
    nav_interview: "Interview",
    nav_moments: "Moments",
    nav_personality: "Personality",
    nav_philosophy: "Philosophy",
    nav_skills: "Skills",
    ne0: "1. Rapidly restores energy, no post-nap grogginess, relieves afternoon drowsiness.",
    ne1: "2. Soothes stress, calms anxiety, reduces mental rumination.",
    ne2: "3. Relaxes muscles, relieves stiff shoulders/back from prolonged sitting.",
    ne3: "4. Improves focus and mental clarity.",
    ne4: "5. Regulates the nervous system, improving nighttime sleep.",
    ne5: "6. Zero barrier—beginners can practice with ease.",
    ne6: "7. A brief pause from thinking.",
    ns0: "1. Find a quiet space. Lie flat.",
    ns1: "2. Close your eyes, breathe deeply, and relax.",
    ns2: "3. Starting from your toes, slowly move your attention upward through every part of your body to the top of your head. Feel each area relax as you exhale. If your mind wanders, don’t force it back—just continue.",
    ns3: "4. When finished, gently wiggle your fingers and toes, stretch, and only then slowly open your eyes and rise.",
    ns4: "5. 10-20 min per session. Best: lunch break, afternoon rest.",
    moment_unit: "items",
    moment_img_unit: "images",
    moment_img_alt: "Image",
        page_title: "Julian Silas — Personal Homepage",
    personality_card_16pf: "Cattell 16PF Questionnaire",
    personality_card_epq: "Eysenck Personality Questionnaire (Revised)",
    personality_card_neo: "NEO-PI-R Inventory (Revised)",
    personality_16pf: "Cattell 16PF Questionnaire",
    personality_back: "← Back to List",
    personality_back_btn: "← Back to List",
    personality_detail: "Details",
    personality_epq: "Eysenck Personality Questionnaire (Revised)",
    personality_intro: "Three scales, three lenses—a fuller portrait of who I am.",
    personality_neo: "NEO-PI-R Inventory (Revised)",
    personality_overall: "Overall",
    personality_score: "Score",
    personality_title: "Personality",
    personality_trait: "Trait Expression",
    phil_back: "← Back to Philosophy",
    phil_childhood: "How Childhood Shaped Me",
    phil_compound: "Growth Is Compound",
    phil_compound_desc: "Growth Is Compound—improve by 1% each day, and a year from now you are 37.8 times yourself.",
    phil_dream: "Dream Analysis",
    phil_fluid: "World Is Fluid",
    phil_fluid_desc: "World Is Fluid—nothing stays unchanged; adapting is the root of survival and growth.",
    phil_friend: "The Kind of People I Befriend",
    phil_love: "My Understanding of Love",
    phil_practice: "Practice Is the Only Standard",
    phil_practice_desc: "Practice Is the Only Standard—action outweighs speculation; results tell the truth.",
    phil_sorry: "Words for You",

    phil_learn: "Lifelong Learning",
    phil_learn_desc: "Lifelong Learning — Stay hungry, stay foolish. Every day is a chance to learn something new.",
    phil_collapse: "Collapse",
    phil_wx1: "🧭 Life’s Main Storyline: Stop Living by Someone Else’s Script",
    phil_wx2: "🤔 What Sets People Apart?",
    phil_wx_label: "📡 Essays",
    philosophy_intro: "The way I understand the world is also the coordinates where I anchor myself.",
    philosophy_title: "Philosophy",
    register_btn: "Sign Up",
    register_placeholder_pwd: "Password (min 6 chars)",
    register_success: "Registration successful!",
    register_title: "Sign Up",
    skill_d0: "Measuring the city stride by stride, keeping body and will resilient.",
    skill_d1: "On two wheels, feeling the wind and freedom, exploring unknown paths.",
    skill_d2: "A stroll in nature is deeply relaxing.",
    skill_d3: "Sweat on the court—a fleeting instant of focus and power becomes eternal.",
    skill_d4: "Leveraging tools with skill, staying curious and in command of technology.",
    skill_d5: "Books are ladders of cognition—continuous input, continuous internalization.",
    skill_d6: "Life is the most authentic game.",
    skill_d7: "Skilled at dissecting the heart, tracing every ripple to its source.",
    skill_d8: "Reinforce through learning, refine day by day. Compound thinking drives long-term growth.",
    skill_t0: "Running",
    skill_t1: "Cycling",
    skill_t2: "Walking",
    skill_t3: "Tennis",
    skill_t4: "Tech & Tools",
    skill_t5: "Reading",
    skill_t6: "Gaming",
    skill_t7: "Introspection",
    skill_t8: "Self-Iteration",
    skills_intro: "Things that bring warmth and rhythm to life.",
    skills_title: "Skills",
    we0: "1. Rapidly activates the brain, boosting focus for 1-2 hours.",
    we1: "2. Improves circulation, relieving brain fog from sitting.",
    we2: "3. Strengthens heart/lungs and lower-body muscle.",
    we3: "4. Releases stress, lifts mood, reduces anxiety.",
    we4: "5. Combining stairs with flat walking boosts efficiency.",
    we5: "6. Doable anytime, anywhere—no special space needed.",
    ws0: "1. Basic brisk walk: Head up, chest out, arms swinging naturally—pace where you can talk but not sing.",
    ws1: "2. Route: Walk to the corridor end, loop upstairs or downstairs.",
    ws2: "3. Rhythm: The faster, the quicker the activation.",
    ws3: "4. Tip: Adding a light hum while walking boosts the effect.",
    theme_aria: "Toggle theme",
    intimacy_title: "Insufficient Intimacy",
    intimacy_desc: "Dreams are the whispers of the soul, open only to those close enough.",
    intimacy_tip: "Current intimacy level is too low to view this content.",
    intimacy_hint: "💡 Talk more, meet more—intimacy will rise naturally.",
    friend_page_title: "The Kind of People I Befriend",
    love_page_title: "The Truth and Death of Love",
    childhood_page_title: "How Childhood Shaped Me",
    sorry_page_title: "Words for You",
    sorry_poem1_title: "If I Have Ever Hurt You",
    sorry_poem2_title: "If I Was Ever Hurt by You",
    sorry_subtitle1: "“Sorry”",
    sorry_subtitle2: "“Forgiveness”",
    childhood_p1: "As a child, I didn’t understand this saying, because I stood on the receiving end of that scrutiny. In high school, I dismissed it as nonsense—a person’s life has countless variables; how could childhood alone seal a lifelong destiny?",
    childhood_p2: "The core of this proverb is never about predicting a child’s innate quality or life ceiling, but about revealing a simple essence: a child’s every word and deed, their temperament and character, are the combined result of their family, upbringing, and all social relations. It echoes Marx’s classic line: the human being is the sum of all social relations. A child’s image is precisely the composite snapshot of all their social relations. (The superstition of genetic determinism already belongs to the dust of the last century.)",
    childhood_p3: "Eating out today, watching relatives’ children in all their varied forms, I observed and reflected. I suddenly recalled my own childhood: there were always adults who looked at you with the same peculiar gaze I now possess—the name of that gaze is scrutiny. Scrutinizing whether you were worth the investment of their thoughts and guidance, whether their efforts on you would yield expected results rather than go to waste.",
    childhood_p4: "But to them, I was ultimately an outsider. An outsider can do very little: sometimes they can’t help but say an extra word, sometimes they are frustrated by your unfulfilled potential, and in the end they can only tell themselves not to meddle, detach, and withdraw. Now, I have become that outsider.",
    childhood_p5: "Standing on the other side of scrutiny, I finally understand: this scrutiny has nothing to do with gender, age, or education, nor is it the condescending privilege of elders. Its essence is foundational awareness—of child personality development, the psychology behind behavior, the shaping forces of family, environment, and society, and the boundaries of human interaction. It is the inner steadiness not to be swayed by a child’s emotions, the empathic ability to see through surface behavior to the child’s true needs, and the neutral awareness to observe without premature judgment.",
    childhood_p6: "Through a child’s behavior, one can often glimpse the emotional logic behind it, the ingrained behavioral patterns that sustain those emotions, and the foundational life mechanisms shaped by their growth environment, with family education at its core. These mechanisms lay down a profound life undertone in early childhood, becoming the most instinctive, subconscious responses when facing the world. Their influence runs through the entire arc of growth; reshaping and recalibrating them later is no easy feat.",
    childhood_p7: "This also attests to the old saying, “It is easier to move mountains than to change one’s nature.” Deeply reshaping these life mechanisms is essentially a thorough rewriting of one’s inherent cognition and instinctive reactions. This process demands enormous mental energy, sustained by long-term, resolute action, before it can truly succeed.",
    body_nsdr_title: "I. NSDR (Non-Sleep Deep Rest)",
    body_478_title: "II. 4-7-8 Breathing Method",
    body_walk_title: "I. Brisk Walking",
    body_steps_label: "Steps",
    body_effects_label: "Effects",
    love_attachment_p1: "Attachment is an instinctual behavioral system with survival value, designed to protect the young from threat. Different caregiving strategies lead infants to form different attachment styles: secure, avoidant, and anxious-ambivalent. Securely attached adults display trust, stability, and positive expectations in love; avoidant adults tend to maintain emotional distance and feel discomfort with intimacy; anxious-ambivalent adults exhibit excessive preoccupation and insecurity in relationships.",
    love_attachment_p2: "Emotional resonance precedes physical attraction. The caregiver is life’s first template of love—we naturally gravitate toward those who resemble our caregivers in appearance, personality, expression, tone, gesture, and manner of relating. As we continue to fall for different people, the template updates. Neural regions encoding certain traits are reinforced, and when we encounter someone with those traits, that region activates, cascading into the love-related modules—hence love at first sight, or love that grows over time.",
    love_loss_p1: "The opposite of love is not hate, but pain. We are naturally drawn to the familiar and safe. When being seen, valued, favored, and accepted becomes habit, the brain designates the relationship as a “safe zone.” When it ends, we instinctively want to stay put, unable to break free from entrenched emotional patterns.",
    love_loss_p2: "Those with deep attachments are also those who persevere, who endure. Su Shi wrote: “Those who achieve great things in ancient times not only possessed extraordinary talent but also an indomitable will.” Most people lack this—they are ordinary. Pure rationality without regard for emotion is not the way. May this piece help you recognize love’s truth, and amidst reason and emotion, pain and love, find a middle path—without being trapped by attachment.",
    love_unique_p1: "Metaphysical beauty, when deconstructed by reason into tangible, concrete logic, loses its poetry.",
    love_unique_p2: "One can easily like anyone—it is merely hormonal instinct. One can also love all beings, needing only sufficient compassion.",
    love_unique_p3: "The uniqueness of love is the uniqueness of the person—rooted in the soul, sedimented through experience.",
    love_unique_p4: "Is anyone truly irreplaceable? From the physical perspective: genes can be cloned in twins, faces can resemble strangers on the street, and external traits like knowledge, ability, and wealth can all be matched or surpassed by others.",
    love_unique_p5: "Only the soul cannot be replicated. From the metaphysical view downward: from the moment of birth, every second is infinitely dynamic. Every choice you make, every thought you think, every firsthand experience—all the trajectories unique to your life interweave and accumulate, irreplicable by anyone, ultimately forging the one and only you 🫵",

    personality_note: "🧪 Tested: 2025.12  |  Personality evolves dynamically; results reflect my state at that time",
};